### ISSUE TITLE
关于训练数据加载问题

### ISSUE THREAD

**Issue by sjtugzx** [17000cyh/IMDiffusion#6]
想请问下代码里面加载训练数据把训练集和测试集的数据读取之后做了concat，这个步骤的目的是什么，以及这么操作是否会造成数据泄露？

**Comment by 17000cyh** [comment]
您好，相关代码如下：

        length = self.data.shape[0]

        self.mask_ratio = mask_ratio
        self.test_data = pickle.load(
            open(test_path, "rb")
        )
        self.data = np.concatenate([self.data, self.test_data])
        self.data = torch.Tensor(self.data)
        # 为了避免高斯噪声造成的影响过大，此处将原有的数值全部乘以20
        self.data = self.data[:length, :] * 20

我忘记当时写这儿的心路历程，但你可以注意到 “self.data = self.data[:length, :] * 20” ，实际这里的data已经将test_data进行了去除；这应该是我当时编码时候的部分设计变更后草稿忘记去除导致的；后续我会删除这里的代码。

另外关于数据泄露，我理解即使这里的test_data未被去除，也是不会造成数据泄露的。原因是IMDiffusion本质是一个自编码器，它在训练的时候不可能看到任何的异常ground truth信息。

以上

2024-11-29 09:15:05 "Zhixin Guo" ***@***.***> 写道：

想请问下代码里面加载训练数据把训练集和测试集的数据读取之后做了concat，这个步骤的目的是什么，以及这么操作是否会造成数据泄露？
